export const SELECT_VIDEO = "SELECT_VIDEO";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const GET_ALL_VIDEOS = "GET_ALL_VIDEOS";
export const SET_VIDEO_LIST = "SET_VIDEO_LIST";
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING"